# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 22:39
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('answer', models.BooleanField()),
                ('surveyItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.SurveyItem')),
            ],
        ),
    ]
